version: "3.9"
services:
  wedding:
    build: .
    image: wedding-app:latest
    ports:
      - "8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true